name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # If your Dockerfile is not in root directory, specify the path:
          # docker build -f path/to/Dockerfile -t marwen77/mysiteweb:latest .
          
          # Or change directory first:
          # cd path/to/dockerfile/directory
          
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            docker build -t marwen77/mysiteweb:pr-${{ github.event.number }} .
          else
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t marwen77/mysiteweb:latest \
              -t marwen77/mysiteweb:${{ github.sha }} \
              --push .
          fi