name: Build and Push Login Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/login/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/login-service:latest ./backend/login

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/login-service:latest
