name: Build, Test and Push Login Service Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/login/**'  # adapte ce chemin selon la structure exacte de ton repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug – structure du repo
        run: |
          echo "== Contenu racine =="
          ls -1
          echo "== Contenu backend/login =="
          ls -1 backend/login

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: backend/login
        run: npm install

      - name: Run Tests
        working-directory: backend/login
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker buildx build backend/login --tag ${{ secrets.DOCKER_USERNAME }}/login-service:latest --load

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/login-service:latest
