name: Build, Test and Push Login Service Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/login/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug – structure du repo
        run: |
          echo "== Racine du repo =="
          ls -la
          echo "== backend =="
          ls -la backend
          echo "== backend/login =="
          ls -la backend/login

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: backend/login
        run: npm install

      - name: Run Tests
        working-directory: backend/login
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/login-service:latest backend/login

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/login-service:latest
